Repository ultralytics/docs, pull requests merged in 2024-11, with the labels that each got.

#116 Update download_websites.yml
  .github/workflows/download_websites.yml
Labels: devops

#117 Update download_websites.yml
  .github/workflows/download_websites.yml
Labels: enhancement, devops

#121 Update check_domains.yml
  .github/workflows/check_domains.yml
Labels: devops

#119 Update links.yml
  .github/workflows/links.yml
Labels: enhancement, devops

#123 Use new Ultralytics Retry action
  .github/workflows/links.yml
  .github/workflows/links_local.yml
Labels: documentation, enhancement, devops

#124 Use new Ultralytics Retry action
  .github/workflows/links.yml
Labels: enhancement, devops

#125 Fix lychee base-url
  .github/workflows/links.yml
Labels: documentation, devops

#126 Update links.yml
  .github/workflows/links.yml
Labels: devops

#127 Update links.yml to 900s delay
  .github/workflows/links.yml
Labels: devops

#129 Update check_domains.yml
  .github/workflows/check_domains.yml
Labels: enhancement, devops

#130 Update links.yml
  .github/workflows/links.yml
Labels: enhancement, devops

#131 Update check_domains.yml
  .github/workflows/check_domains.yml
Labels: enhancement, devops

#133 Update check_domains.yml
  .github/workflows/check_domains.yml
Labels: devops

#134 Update check_domains.yml
  .github/workflows/check_domains.yml
  .github/workflows/download_websites.yml
  .github/workflows/tag.yml
Labels: devops
