Repository ultralytics/docs, pull requests merged in 2024-08, with the labels that each got.

#81 Update links.yml for more retries
  .github/workflows/links.yml
Labels: enhancement

#82 Update links.yml to accept 401
  .github/workflows/links.yml
Labels: enhancement

#84 Ultralytics Actions JSON, CSS and autolabel support
  .github/workflows/format.yml
Labels: documentation, enhancement

#85 Fix tesla links
  .github/workflows/links.yml
Labels: enhancement, dependencies

#86 Remove hi and nl
  .github/workflows/links.yml
  .github/workflows/sitemaps.yml
Labels: documentation, enhancement

#87 Update GCS submission for www subdomain in sitemaps.yml
  .github/workflows/sitemaps.yml
Labels: enhancement

#89 Exclude "/[a-z][a-z]/"
  .github/workflows/links.yml
Labels: enhancement, dependencies

#91 Add https://www.reddit.com/r/Ultralytics/ badge
  .github/workflows/links.yml
Labels: documentation, enhancement

#97 Update download_websites.yml
  .github/workflows/download_websites.yml
  README.md
Labels: documentation, enhancement

#98 --force-directories
  .github/workflows/links.yml
Labels: enhancement

#99 Improved broken link checks
  .github/workflows/links.yml
  .github/workflows/links_local.yml
Labels: enhancement

#101 Add tag action
  .github/workflows/links.yml
  .github/workflows/tag.yml
Labels: documentation, enhancement

#103 Update tag.yml
  .github/workflows/tag.yml
Labels: enhancement, dependencies
