Repository ultralytics/docs, pull requests merged in 2024-10, with the labels that each got.

#111 Update check_domains.yml with YOLO domains
  .github/workflows/check_domains.yml
Labels: enhancement

#112 Ultralytics Code Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
  .github/workflows/tag.yml
  README.md
Labels: documentation, enhancement

#113 Update tag.yml
  .github/workflows/tag.yml
Labels: enhancement, dependencies

#114 Update links.yml
  .github/workflows/links.yml
Labels: documentation

#115 Update check_domains.yml
  .github/workflows/check_domains.yml
Labels: enhancement
