Repository ultralytics/docs, pull requests merged in 2025-08, with the labels that each got.

#215 Add Bund to spellcheck ignore words
  .github/workflows/links.yml
Labels: documentation, enhancement

#216 Simplify lychee install in links.yml
  .github/workflows/links.yml
Labels: documentation, devops

#218 Remove ultralytics.dev from check_domains.yml
  .github/workflows/check_domains.yml
Labels: documentation, devops

#222 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/links.yml
  .github/workflows/links_local.yml
  README.md
  docs/en/compare/yolov5-vs-yolov6.md
  docs/en/compare/yolov6-vs-yolov5.md
Labels: documentation, devops

#223 Potential fix for code scanning alert no. 3: Workflow does not contain permissions
  .github/workflows/links.yml
Labels: enhancement, devops

#225 Potential fix for code scanning alert no. 9: Workflow does not contain permissions
  .github/workflows/tag.yml
Labels: devops
