Repository ultralytics/docs, pull requests merged in 2025-01, with the labels that each got.

#139 Update links.yml
  .github/workflows/links.yml
Labels: enhancement, devops

#140 Update format.yml
  .github/workflows/format.yml
Labels: enhancement, devops

#141 Update links.yml
  .github/workflows/links.yml
Labels: enhancement, devops

#143 Try headers fix for timeouts
  .github/workflows/links.yml
Labels: documentation, enhancement, devops

#144 Update links_local.yml
  .github/workflows/links_local.yml
Labels: enhancement, devops

#145 Return [TIMEOUT] lines
  .github/workflows/links.yml
Labels: enhancement, devops

#146 Add `community` and `handbook` subdomains to broken link checks
  .github/workflows/links.yml
Labels: documentation, enhancement, devops

#147 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
  .github/workflows/links.yml
Labels: enhancement, devops

#148 Commet duplicated ESCAPED_SUMMARY
  .github/workflows/links.yml
Labels: enhancement, devops

#150 Standardize license headers in TOML/YAML files
  .github/dependabot.yml
  .github/workflows/check_domains.yml
  .github/workflows/download_websites.yml
  .github/workflows/format.yml
  .github/workflows/links.yml
  .github/workflows/links_local.yml
  .github/workflows/sitemaps.yml
  .github/workflows/stale.yml
  .github/workflows/tag.yml
Labels: documentation

#151 Update download_websites.yml to reject languages
  .github/workflows/download_websites.yml
Labels: documentation, devops

#152 Update links.yml
  .github/workflows/links.yml
Labels: documentation, devops

#154 Add spellchecks to actions
  .github/workflows/links.yml
Labels: documentation, devops

#155 Expand spelling `--ignore-words` list
  .github/workflows/links.yml
Labels: documentation, devops

#156 Ignore URLs for spelling
  .github/workflows/links.yml
Labels: documentation, devops

#157 Simplify links titles
  .github/workflows/links.yml
Labels: enhancement, devops

#158 Add .idea dir to gitignore
  .gitignore
Labels: enhancement, devops

#160 Update links.yml
  .github/workflows/links.yml
Labels: documentation, devops

#161 Fix broken links
  docs/en/compare/yolo11-vs-damo-yolo.md
  docs/en/compare/yolov9-vs-damo-yolo.md
Labels: documentation

#163 Add PP-YOLOE+ Params and FLOPs
  docs/en/compare/damo-yolo-vs-pp-yoloe.md
  docs/en/compare/pp-yoloe-vs-damo-yolo.md
  docs/en/compare/pp-yoloe-vs-rtdetr.md
  docs/en/compare/pp-yoloe-vs-yolo11.md
  docs/en/compare/pp-yoloe-vs-yolov10.md
  docs/en/compare/pp-yoloe-vs-yolov5.md
  docs/en/compare/pp-yoloe-vs-yolov7.md
  docs/en/compare/pp-yoloe-vs-yolov8.md
  docs/en/compare/pp-yoloe-vs-yolov9.md
  docs/en/compare/pp-yoloe-vs-yolox.md
  docs/en/compare/rtdetr-vs-pp-yoloe.md
  docs/en/compare/yolo11-vs-pp-yoloe.md
  docs/en/compare/yolov10-vs-pp-yoloe.md
  docs/en/compare/yolov5-vs-pp-yoloe.md
  docs/en/compare/yolov7-vs-pp-yoloe.md
  docs/en/compare/yolov8-vs-pp-yoloe.md
  docs/en/compare/yolov9-vs-pp-yoloe.md
  docs/en/compare/yolox-vs-pp-yoloe.md
Labels: documentation, enhancement

#164 Add PP-YOLOE+ Params and FLOPs
  docs/en/compare/damo-yolo-vs-yolov5.md
  docs/en/compare/pp-yoloe-vs-yolov5.md
  docs/en/compare/yolo11-vs-yolov5.md
  docs/en/compare/yolov5-vs-yolov6.md
  docs/en/compare/yolov6-vs-yolov5.md
  docs/en/compare/yolov7-vs-efficientdet.md
  docs/en/compare/yolov8-vs-rtdetr.md
  docs/en/compare/yolox-vs-efficientdet.md
Labels: documentation

#165 Remove extra html strings
  docs/en/compare/efficientdet-vs-rtdetr.md
  docs/en/compare/pp-yoloe-vs-yolov9.md
  docs/en/compare/yolov10-vs-yolov6.md
  docs/en/compare/yolov5-vs-yolov7.md
  docs/en/compare/yolov6-vs-yolov7.md
  docs/en/compare/yolov9-vs-efficientdet.md
Labels: documentation
