Repository ultralytics/docs, pull requests merged in 2025-03, with the labels that each got.

#174 Exclude x.com from link checks
  .github/workflows/links.yml
Labels: enhancement, devops

#175 Add https://youtu.be/POlQ8MIHhlM to docs
  docs/en/compare/index.md
Labels: documentation, enhancement

#176 Update yolox-vs-yolov10.md
  docs/en/compare/damo-yolo-vs-yolo11.md
  docs/en/compare/yolo11-vs-rtdetr.md
  docs/en/compare/yolov6-vs-yolo11.md
  docs/en/compare/yolov6-vs-yolov10.md
  docs/en/compare/yolox-vs-yolov10.md
Labels: documentation

#177 Update README.md
  README.md
Labels: documentation

#179 Update README.md
  README.md
Labels: documentation
