Repository ultralytics/docs, pull requests merged in 2025-06, with the labels that each got.

#192 Update `links.yml`
  .github/workflows/links.yml
Labels: documentation, devops

#196 Update links.yml
  .github/workflows/links.yml
Labels: enhancement, devops

#200 Update Meituan links
  docs/en/compare/damo-yolo-vs-rtdetr.md
  docs/en/compare/efficientdet-vs-pp-yoloe.md
  docs/en/compare/pp-yoloe-vs-yolov5.md
  docs/en/compare/pp-yoloe-vs-yolov6.md
  docs/en/compare/yolov10-vs-yolov6.md
  docs/en/compare/yolov5-vs-yolov6.md
  docs/en/compare/yolov6-vs-efficientdet.md
  docs/en/compare/yolov6-vs-pp-yoloe.md
  docs/en/compare/yolov6-vs-rtdetr.md
  docs/en/compare/yolov6-vs-yolo11.md
  docs/en/compare/yolov6-vs-yolov5.md
  docs/en/compare/yolov6-vs-yolov7.md
  docs/en/compare/yolov6-vs-yolov8.md
  docs/en/compare/yolov6-vs-yolov9.md
  docs/en/compare/yolov6-vs-yolox.md
  docs/en/compare/yolov7-vs-rtdetr.md
  docs/en/compare/yolov9-vs-yolov6.md
Labels: documentation

#201 Fix YOLO11 names
  docs/en/compare/damo-yolo-vs-pp-yoloe.md
  docs/en/compare/damo-yolo-vs-yolov6.md
  docs/en/compare/damo-yolo-vs-yolox.md
  docs/en/compare/efficientdet-vs-yolov6.md
  docs/en/compare/efficientdet-vs-yolov8.md
  docs/en/compare/pp-yoloe-vs-damo-yolo.md
  docs/en/compare/pp-yoloe-vs-rtdetr.md
  docs/en/compare/rtdetr-vs-yolov10.md
  docs/en/compare/rtdetr-vs-yolov6.md
  docs/en/compare/yolov6-vs-yolov10.md
  docs/en/compare/yolov8-vs-rtdetr.md
  docs/en/compare/yolov9-vs-yolov7.md
Labels: documentation

#202 Update links.yml
  .github/workflows/links.yml
  docs/en/compare/damo-yolo-vs-rtdetr.md
  docs/en/compare/efficientdet-vs-pp-yoloe.md
  docs/en/compare/yolov7-vs-rtdetr.md
Labels: documentation, devops
